src/main/java/org/imixs/application/model/ModelController.java
/*******************************************************************************
 *  Imixs Workflow 
 *  Copyright (C) 2001, 2011 Imixs Software Solutions GmbH,  
 *  http://www.imixs.com
 *  
 *  This program is free software; you can redistribute it and/or 
 *  modify it under the terms of the GNU General Public License 
 *  as published by the Free Software Foundation; either version 2 
 *  of the License, or (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, 
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 *  General Public License for more details.
 *  
 *  You can receive a copy of the GNU General Public
 *  License at http://www.gnu.org/licenses/gpl.html
 *  
 *  Project: 
 *  	http://www.imixs.org
 *  	http://java.net/projects/imixs-workflow
 *  
 *  Contributors:  
 *  	Imixs Software Solutions GmbH - initial API and implementation
 *  	Ralph Soika - Software Developer
 *******************************************************************************/

package org.imixs.application.model;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.parsers.ParserConfigurationException;

import org.imixs.workflow.FileData;
import org.imixs.workflow.ItemCollection;
import org.imixs.workflow.bpmn.BPMNUtil;
import org.imixs.workflow.engine.ModelService;
import org.imixs.workflow.engine.WorkflowService;
import org.imixs.workflow.exceptions.AccessDeniedException;
import org.imixs.workflow.exceptions.ModelException;
import org.imixs.workflow.faces.data.WorkflowController;
import org.openbpmn.bpmn.BPMNModel;
import org.openbpmn.bpmn.exceptions.BPMNModelException;
import org.openbpmn.bpmn.util.BPMNModelFactory;
import org.xml.sax.SAXException;

import jakarta.ejb.EJB;
import jakarta.enterprise.context.RequestScoped;
import jakarta.faces.event.ActionEvent;
import jakarta.inject.Inject;
import jakarta.inject.Named;

/**
 * The ModelController provides informations about workflow models.
 * 
 * A ModelVersion is always expected in the format
 * 
 * 'DOMAIN-LANGUAGE-VERSIONNUMBER'
 * 
 * e.g. office-de-0.1, support-en-2.0, system-de-0.0.1
 * 
 * 
 * @author rsoika
 * 
 */
@Named
@RequestScoped
public class ModelController implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	protected ModelUploadHandler modelUploadHandler;

	@Inject
	WorkflowController workflowController;

	@EJB
	protected ModelService modelService;

	@EJB
	protected WorkflowService workflowService;

	private static final Logger logger = Logger.getLogger(ModelController.class.getName());

	/**
	 * returns all groups for a version
	 * 
	 * @param version
	 * @return
	 */
	public Set<String> getGroups(String version) {
		try {
			BPMNModel model;
			model = modelService.getModelManager().getModel(version);
			return modelService.getModelManager().findAllGroupsByModel(model);
		} catch (ModelException e) {
			logger.log(Level.WARNING, "Unable to load groups:{0}", e.getMessage());
		}
		// return empty result
		return new LinkedHashSet<>();
	}

	/**
	 * Returns a sorted list of all WorkflowGroups from all models.
	 * 
	 * Workflow groups of the system model will be skipped.
	 * 
	 * A workflowGroup with a '~' in its name will be skipped. This indicates a
	 * child process.
	 * 
	 * The worflowGroup list is used to assign a workflow Group to a core process.
	 * 
	 * @return list of workflow groups
	 * @throws ModelException
	 */
	public List<String> getWorkflowGroups() throws ModelException {

		List<String> result = new ArrayList<>();
		for (BPMNModel model : modelService.getModelManager().getAllModels()) {
			String version = BPMNUtil.getVersion(model);
			// Skip system model..
			if (version.startsWith("system-")) {
				continue;
			}
			Set<String> groups = modelService.getModelManager().findAllGroupsByModel(model);
			for (String groupName : groups) {
				if (result.contains(groupName))
					continue;
				if (groupName.contains("~"))
					continue;
				result.add(groupName);
			}
		}

		Collections.sort(result);
		return result;

	}

	/**
	 * Finds the first matching model version for a group name
	 * 
	 * @param group
	 * @return
	 * @throws ModelException
	 */
	public String findVersionByGroup(String group) throws ModelException {
		return modelService.getModelManager().findVersionByGroup(group);
	}

	/**
	 * Loads the first start task in the corresponding workflow group
	 * 
	 * @param group
	 * @return
	 * @throws ModelException
	 */
	public ItemCollection findStartTaskByGroup(String version, String group) throws ModelException {
		ItemCollection result = null;
		BPMNModel model = modelService.getModelManager().getModel(version);
		List<ItemCollection> startTasks;

		startTasks = modelService.getModelManager().findStartTasks(model, group);
		if (startTasks.size() > 0) {
			result = startTasks.get(0);
		}

		if (result == null) {
			logger.warning("No Model found for Group '" + group + "'");
		}

		return result;

	}

	/**
	 * Creates a new process instance based on a given start task in the
	 * corresponding workflow model
	 * group
	 * 
	 * @param version   - model version
	 * @param startTask - initial task
	 * @return new process instance
	 * @throws ModelException
	 */
	public ItemCollection startWorkflowByTask(String version, ItemCollection startTask) throws ModelException {
		ItemCollection result = null;
		workflowController.create(version, startTask.getItemValueInteger("numprocessid"), null);
		if (result == null) {
			logger.warning("No Model found for model version '" + version + "'");
		}
		return result;

	}

	/**
	 * Returns a sorted set of all model versions.
	 * <p>
	 * Used by the Model View.
	 * 
	 * @return
	 */
	public Set<String> getVersions() {
		return modelService.getModelEntityStore().keySet();
	}

	/**
	 * Returns a Model Entity. Used by the Model View
	 * 
	 * @param version
	 * @return
	 */
	public ItemCollection getModelEntity(String version) {
		return modelService.loadModel(version);
	}

	/**
	 * This method adds all uploaded model files. The method tests the model type
	 * (.bmpm, .ixm). BPMN Model will be handled by the ImixsBPMNParser. A .ixm file
	 * will be imported using the default import mechanism.
	 * 
	 * @param event
	 * @throws IOException
	 * @throws SAXException
	 * @throws ParserConfigurationException
	 * @throws ParseException
	 * @throws ModelException
	 * 
	 */
	public void doUploadModel(ActionEvent event)
			throws ModelException {
		List<FileData> fileList = modelUploadHandler.getModelUploads().getFileData();

		if (fileList == null) {
			return;
		}
		for (FileData file : fileList) {

			// test if bpmn model?
			if (file.getName().endsWith(".bpmn")) {
				InputStream inputStream = new ByteArrayInputStream(file.getContent());
				BPMNModel model;
				try {
					model = BPMNModelFactory.read(inputStream);
					modelService.saveModel(model);
					continue;
				} catch (BPMNModelException e) {
					throw new ModelException(ModelException.INVALID_MODEL,
							"Unable to read model file: " + file.getName(), e);
				}
			} else {
				// model type not supported!
				logger.log(Level.WARNING, "Invalid Model Type. Model {0} can't be imported!", file.getName());
			}
		}
		modelUploadHandler.reset();
	}

	/**
	 * This Method deletes the given model from the database and the internal model
	 * cache.
	 * 
	 * @param modelversion
	 * @throws AccessDeniedException
	 * @throws ModelException
	 */
	public void deleteModel(String modelversion) throws AccessDeniedException, ModelException {
		modelService.deleteModel(modelversion);
	}

}

src/main/webapp/pages/workitems/error.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs">


	<h:panelGroup rendered="#{! empty facesContext.maximumSeverity}">
		<div class="ui-widget" style="margin:20px 0;">
			<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;">
				<p>
					<span class="ui-icon ui-icon-alert"
						style=" margin-right: .3em;"></span> <strong>Error:</strong>
					<h:messages />
				</p>
			</div>
		</div>
	</h:panelGroup>
</ui:composition>

src/main/webapp/pages/workitems/start.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs"
	template="/layout/template.xhtml">




	<f:metadata>
		<f:viewAction action="#{workflowController.onLoad()}" />
	</f:metadata>



	<ui:define name="content">
		<f:view>
			<h:form id="workitem_form_id">

				<h1>Start a New Business Process</h1>
				<p class="lead">Select a Workflowgroup to start a new task:</p>


				<!-- Error  -->
				<ui:include src="error.xhtml" />


				<ul style="margin: 5px 0;">
					<ui:repeat value="#{modelController.workflowGroups}" var="group">
						<!-- get first task by group -->
						<ui:param name="version" value="#{modelController.findVersionByGroup(group)}" />
						<ui:param name="initialTask" value="#{modelController.findStartTaskByGroup(version,group)}" />
						<li>
							<h:panelGroup rendered="#{!empty initialTask}">
								<h:commandLink title=" " styleClass="action-create"
									actionListener="#{modelController.startWorkflowByTask(version,initialTask)}"
									action="/pages/workitems/workitem">
									<span class="typcn typcn-folder-add" style="margin-right:5px;"></span>
									<h:outputText value="#{group}" />
								</h:commandLink>
								<p>
									<h:outputText value="#{initialTask.item['rtfdescription']}" escape="false" />
								</p>
								<span class="imixs-tooltip">
									<h:outputText value="#{initialTask.item['rtfdescription']}" escape="false" />
								</span>
							</h:panelGroup>
							<h:outputText style="color:red" rendered="#{empty initialTask}"
								value="Model not found: #{group}"></h:outputText>
						</li>
					</ui:repeat>
				</ul>


			</h:form>
		</f:view>
	</ui:define>

</ui:composition>

src/main/webapp/pages/workitems/sub_documents.xhtml
<f:subview id="sub_documents" xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs">

	<dl>
		<dt style="clear: left;">
			<h:outputText value="#{message.attachments}" />
		</dt>
		<dd>
			<i:imixsFileUpload id="file_upload_id" workitem="#{workflowController.workitem}"
				context_url="#{facesContext.externalContext.requestContextPath}/api/workitems/workitem/#{workflowController.workitem.item['$uniqueid']}"
				hideattachments="false" />
		</dd>
	</dl>



	<!-- Documents Preview -->


	<!-- Note: the document height can be adjusted with the ui:param 'height' -->
	<script type="text/javascript">
		/*<![CDATA[*/

		/* reqlace special characters in attachemnt url */
		$(document).ready(
			function () {

				// hide documents-file-deeplink
				$("#documents-file-deeplink").hide();

				// update the link action for each file
				// we redirect the href into the iframe target
				$(".imixsFileUpload_uploadlist .imixsFileUpload_file").each(
					function (index, element) {
						$(this).click(function () {
							var file_link = $(this).attr('href');
							updateIframe(file_link);

							// update documents-file-deeplink
							$("#documents-file-deeplink").attr('href', file_link);
							$("#documents-file-deeplink").show();

							// cancel link
							return false;
						});
					});

				// autoload feature - load first pdf if available
				$(".imixsFileUpload_uploadlist .imixsFileUpload_file").each(
					function (index, element) {
						var attachmentName = $(this).text();
						if (attachmentName.endsWith('.pdf') || attachmentName.endsWith('.PDF')) {
							$(this).click();
							return false;
						}
					});



			});


		function updateIframe(docurl) {
			//console.log(docurl);
			$("#document_preview_helper").hide();
			var iframe = document.getElementById('imixs_dms_iframe');
			iframe.src = docurl;
		}
		/*]]>*/
	</script>


	<ui:param name="fileData" value="#{workflowController.workitem.fileData}"></ui:param>

	<div class="imixs-form-section imixs-form-attachments">

		<a href="#" class="pull-right" id="documents-file-deeplink" target="_blank"><span
				class="typcn typcn-cloud-storage" style="font-size:1.2em;"></span> Download</a>

		<ui:fragment rendered="#{! empty fileData}">
			<iframe id="imixs_dms_iframe" src="" width="100%" height="#{empty height?800:height}px">
			</iframe>
		</ui:fragment>


	</div>





</f:subview>

src/main/webapp/pages/workitems/sub_main.xhtml
<f:subview id="sub_main" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs">

	<!-- **** General info ***** -->
	
	
	
	
	<dl>
		<dt>
			<h:outputLabel value="#{message.subject}">
				<h:message style="color: red" for="subject_id" showSummary="true"
					showDetail="false" />
			</h:outputLabel>
		</dt>
		<dd style="width: 400px;">
			<h:inputText style="width: 20em;" required="true"
				value="#{workflowController.workitem.item['subject']}"
				id="subject_id">
			</h:inputText>
		</dd>

		<dt>
			<h:outputLabel value="#{message.date}"></h:outputLabel>
		</dt>
		<dd style="width: 350px;">
			<i:imixsDateInput value="#{workflowController.workitem.item['date']}"  showtime="true" minuteinterval="5"/>
		</dd>

		<dt style="clear: left;">
			<h:outputLabel value="Team:">
				<h:message style="color: red" for="team_id" showSummary="true"
					showDetail="false" />
			</h:outputLabel>
		</dt>
		


		<dt style="clear: left;">#{message.details}</dt>
		<dd>
			<h:inputTextarea class="imixs-editor"
				value="#{workflowController.workitem.item['description']}" />

		</dd>
	</dl>

	<div style="clear: left;" />



</f:subview>

src/main/webapp/pages/workitems/sub_workflowtoolbar.xhtml
<f:subview id="sub_workflowtoolbar" xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs">


	<div class="imixs-panel">
		<h2>#{message.workflow}</h2>


		<!-- **** Workflow Actions only visible if user is autor ***** -->
		<ui:fragment
			rendered="#{empty workflowController.workitem.item['$lastevent'] or workflowController.workitem.item['$isauthor']}">
			<i:imixsWorkflowActions workflowController="#{workflowController}" disabletooltip="false" />
		</ui:fragment>
		<ui:fragment
			rendered="#{!(empty workflowController.workitem.item['$lastevent'] or workflowController.workitem.item['$isauthor'])}">
			<p style="color: red">You are not allowed to edit this Workitem!</p>
		</ui:fragment>

		<h:commandButton value="#{message.close}" action="/pages/my_tasklist?faced-redirect=true"
			actionListener="#{workflowController.close()}" />





		<dl>
			<!-- ### Kommentar ### -->
			<dt class="imixs-no-print">
				<h:outputLabel value="#{message['comment']}:" />
			</dt>
			<dd>
				<h:inputTextarea value="#{workflowController.workitem.item['txtComment']}" />
			</dd>
		</dl>

		<h:panelGrid columns="3">
			<h:outputLabel value="#{message.created}: " />
			<h:outputText value="#{workflowController.workitem.item['$created']} ">
				<f:convertDateTime timeZone="CET" type="both" dateStyle="medium" />
			</h:outputText>
			<h:outputText value=" #{message.by} #{workflowController.workitem.item['namcreator']} " />
			<h:outputLabel value="#{message.modified}: " />
			<h:outputText value="#{workflowController.workitem.item['$modified']} ">
				<f:convertDateTime timeZone="CET" type="both" dateStyle="medium" />
			</h:outputText>
			<h:outputText value=" #{message.by} #{workflowController.workitem.item['namcurrenteditor']}" />
		</h:panelGrid>



		<div class="imixs-tabs">
			<ul>
				<li><a href="#tab-1">Activities</a></li>
				<li><a href="#tab-2">Documents</a></li>

			</ul>
			<div id="tab-1">

				<ui:include src="/pages/workitems/workitem_chronicle.xhtml" />
			</div>
			<div id="tab-2">
				<ui:include src="/pages/workitems/sub_documents.xhtml" />



			</div>

		</div>



	</div>



</f:subview>

src/main/webapp/pages/workitems/workitem.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs"
	template="/layout/template.xhtml">




	<f:metadata>
		<f:viewAction action="#{workflowController.onLoad()}" />
	</f:metadata>

	<ui:define name="content">
		<f:view>
			<h:form id="workitem_form_id">

				<div class="row">
					<div class="col-7" style="border-right: 1px solid #ccc;">

						<h2>#{workflowController.workitem.item['$WorkflowGroup']} ▹
							#{workflowController.workitem.item['$WorkflowStatus']}</h2>

						<!-- Error  -->
						<ui:include src="error.xhtml" />

						<ui:fragment rendered="#{! empty customFormController.sections}">
							<!-- Display the custom form  -->
							<ui:include src="/pages/workitems/forms/custom.xhtml">
								<ui:param name="workitem" value="#{workflowController.workitem}" />
							</ui:include>
						</ui:fragment>
						<ui:fragment rendered="#{empty customFormController.sections}">
							<p class="lead">You process definition does not define any form elements. You can add a form
								layout by your model
							</p>
							<p>Example:</p>
							<pre class="code">
&lt;?xml version=&quot;1.0&quot;?&gt;
&lt;imixs-form&gt;
  &lt;imixs-form-section&gt;
    &lt;item name=&quot;_descripton&quot; type=&quot;textarea&quot;
        label=&quot;Short Description&quot; /&gt;
  &lt;/imixs-form-section&gt;
  &lt;imixs-form-section&gt;
    &lt;item name=&quot;_details&quot; type=&quot;html&quot; label=&quot;Description&quot; /&gt;
  &lt;/imixs-form-section&gt;
&lt;/imixs-form&gt;
							 </pre>
						</ui:fragment>
					</div>


					<div class="col-5">
						<!-- **** Workflow Actions & History  ***** -->
						<ui:include src="/pages/workitems/sub_workflowtoolbar.xhtml" />
					</div>
				</div>
			</h:form>
		</f:view>
	</ui:define>

</ui:composition>

src/main/webapp/pages/workitems/workitem_chronicle.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:marty="http://xmlns.jcp.org/jsf/composite/marty"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs">



	<!-- Main panel - shows entries filtered by optional category -->
	<h:panelGroup id="chronicle-main" layout="block" class="imixs-workitem-chronicle">

		<table style="width: 100%;">
			<!-- print a headline for each year -->
			<ui:repeat var="year" value="#{chronicleController.getYears()}">

				<!-- print YEAR -->
				<tr class="year">
					<td colspan="3"><h2
							style="width: 100%; text-align: center; border-bottom: 1px solid #ddd;">#{year}</h2></td>
				</tr>

				<!-- print all MONTHs -->
				<ui:repeat var="month"
					value="#{chronicleController.getMonths(year)}">
					<ui:param name="message_month" value="month_#{month}"></ui:param>
					<tr class="month">
						<td colspan="3"><h3 style="width: 100%; text-align: center;">#{message[message_month]}</h3></td>

					</tr>

					<!-- show chronic by month -->
					<ui:repeat var="chronicle"
						value="#{chronicleController.getChroniclePerMonth(year,month)}">
						<ui:include src="workitem_chronicle_entry.xhtml">
							<ui:param name="chronicle" value="#{chronicle}" />
						</ui:include>
					</ui:repeat>
				</ui:repeat>
			</ui:repeat>
		</table>
	</h:panelGroup>

</ui:composition>

src/main/webapp/pages/workitems/workitem_chronicle_entry.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:marty="http://xmlns.jcp.org/jsf/composite/marty"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs">


	
	<!-- 1) User Icon and Time -->
	<tr class="header">
		<td style="width: 160px; vertical-align: top;">
		
			<h:graphicImage
				styleClass="imixs-workitem-chronicle-usericon"
				title="#{chronicle.user}"
				value="https://www.gravatar.com/avatar/#{chronicle.user}?d=identicon">
			</h:graphicImage> 
			<!-- optional - user initials --> 
			<h:outputText value="#{chronicle.date}"
				class="date">
				<f:convertDateTime timeZone="#{message.timeZone}" type="both"
					pattern="#{message.dateTimePattern}" />
			</h:outputText> - #{chronicle.user}</td>
	</tr>



	<!-- print all entries by time descending -->



	<!-- Print History.... -->
	<ui:repeat var="entry" value="#{chronicle.entries}">

		<!-- history -->
		<ui:fragment rendered="#{'history' eq entry.item['type']}">
			<tr class="entry history">
				<td>
					<div class="image-block">
						<h:panelGroup pt:title="#{message.history} #{entry.item['date']}"
							styleClass="typcn typcn-equals-outline"></h:panelGroup>
					</div>

					<div class="content-block">
						<h:outputText escape="false" styleClass="imixs-comments-entry"
							value="#{entry.item['message']}" />
					</div>
				</td>
			</tr>
		</ui:fragment>


		<!-- comment -->
		<ui:fragment rendered="#{'comment' eq entry.item['type']}">
			<tr class="entry comment">
				<td>
					<div class="image-block">
						<h:panelGroup pt:title="#{message.comment} #{entry.item['date']}"
							styleClass="typcn typcn-message"></h:panelGroup>
					</div>
					<div class="content-block">
						<h:panelGroup styleClass="imixs-comments-entry">
							<h:outputText value="#{entry.item['message']}" />
						</h:panelGroup>
					</div>
				</td>
			</tr>
		</ui:fragment>

	</ui:repeat>





</ui:composition>